[phases.setup]
nixPkgs = ["nodejs_20", "chromium", "nss", "freetype", "harfbuzz", "wget"]

[phases.build]
cmds = ["npm install", "npx puppeteer browsers install chrome"]

[start]
cmd = "node server/index.js"
